name: Hello Lambda Pipeline

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.STAGING_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Install SAM + jq
        run: |
          pip install aws-sam-cli
          sudo apt-get install -y jq

      - name: Deploy Staging
        run: |
          sam build
          sam deploy \
            --stack-name hello-staging \
            --parameter-overrides Stage=staging \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Extract API URL
        run: |
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name hello-staging \
            --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
            --output text)

          if [ "$API_URL" == "None" ] || [ -z "$API_URL" ]; then
            echo "Error: ApiUrl output not found in stack."
            exit 1
          fi

          echo "STAGING_API_URL=$API_URL" >> $GITHUB_ENV

      - name: Hit Staging API (wait for readiness)
        run: |
          echo "Waiting for API to become ready..."
          for i in {1..10}; do
            echo "Attempt $i..."
            if curl -f "$STAGING_API_URL/hello"; then
              echo "API is live!"
              exit 0
            fi
            sleep 15
          done

          echo "API did not become ready in time"
          exit 1
      - name: Install Newman
        run: npm install -g newman
      - name: Run Newman Tests
        run: |
          for i in {1..5}; do
            echo "Newman attempt $i..."
            if newman run postman/hello.postman_collection.json \
              --env-var "baseUrl=$STAGING_API_URL"; then
              echo "Contract tests passed"
              exit 0
            fi
            sleep 10
          done
          echo "Contract tests failed"
          exit 1
 

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Configure AWS (Prod)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.PROD_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Install SAM
        run: pip install aws-sam-cli

      - name: Deploy Production
        run: |
          sam build
          sam deploy \
            --stack-name hello-prod \
            --parameter-overrides Stage=prod \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
